version: '3.7'

services:

# -------- RabbitMQ --------
  rabbitmq:
    image: rabbitmq:3.5.3-management
    
    container_name: rabbitmq

    ports:
      - "5672:5672"
      - "15672:15672"
      
    restart: always
   
    networks:
      - currency-compose-network

# -------- Zipkin Server --------
  zipkin-server:
    image: openzipkin/zipkin
    
    container_name: zipkin
    
    environment:
      STORAGE_TYPE: mem
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672

    ports:
      - "9411:9411"
      
    restart: always
    
    depends_on:
      - rabbitmq
   
    networks:
      - currency-compose-network
      
# -------- Eureka Naming Server --------
  naming-server:
    image: rhsb/netflix-eureka-naming-server:0.0.1-SNAPSHOT

    container_name: eureka-naming-server
    
    ports:
      - "8761:8761"
      
    restart: always
   
    networks:
      - currency-compose-network
      
# -------- Zuul Api Gateway --------
  zuul-api-gateway:
    image: rhsb/netflix-zuul-api-gateway-server:0.0.1-SNAPSHOT
    
    container_name: zuul-api-gateway
    
    environment:
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672

    ports:
      - "8765:8765"
      
    restart: always
    
    depends_on:
      - naming-server
      - rabbitmq
      - zipkin-server
   
    networks:
      - currency-compose-network
     
# -------- Currency Exchange Service --------      
  currency-exchange-service:
    image: rhsb/currency-exchange-service:0.0.1-SNAPSHOT
    
    environment:
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672

    ports:
      - "8000:8000"
      
    restart: always
    
    depends_on:
      - naming-server
      - rabbitmq
      - zipkin-server
   
    networks:
      - currency-compose-network    

# -------- Currency Conversion Service --------
  currency-conversion-service:
    image: rhsb/currency-conversion-service:0.0.1-SNAPSHOT
    
    environment:
#      CURRENCY_EXCHANGE_URI: http://currency-exchange-service:8000
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    
    ports:
      - "8100:8100"
      
    restart: always
    
    depends_on:
      - currency-exchange-service
      - naming-server
      - rabbitmq
      - zipkin-server
      
    networks:
      - currency-compose-network
  
# Networks to be created to facilitate communication between containers
networks:
  currency-compose-network: